AWSTemplateFormatVersion: '2010-09-09'
Description: This stack create ECS Fargate Cluster
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV/QA)
    AllowedValues: ['DEV', 'QA']
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: API-GW-ECS-CLUSTER

Outputs:
  ClusterName:
    Description: Name of the ECS cluster
    Value: !Ref 'ECSCluster'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'ClusterName' ] ]