AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates S3 bucket to store Lambda functions
Resources:
  LambdaBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: asakchris-api-gw-lambda
Outputs:
  LambdaBucket:
    Description: Name of Lambda Bucket
    Value: !Ref 'LambdaBucket'
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'LambdaBucket' ] ]