server:
  port: 8000
  servlet:
    context-path: /api/v1/gw/token

management:
  server:
    port: 8001
  endpoints:
    web:
      exposure:
        include: health, info, metrics

spring:
  application:
    name: Token-Service